### ISSUE TITLE
Reason why it only works with "dev-master"?

### ISSUE THREAD

**Issue by markvaneijk** [franzliedke/studio#77] opened 2017-09-06 09:40 UTC
I would like to know if there is a reason why "studio load" and then composer install/update only works when the composer.json requires the package as a "dev-master" version? I would like to specify the version with "*", so I don't need to change it every time I work on a package (and forget to change it back when commiting).

**Comment by rask** [comment] 2017-09-26 20:16
This is a known problem with a fix in the works if I remember correctly. After the fix lands you can `create` and `load` a local package with Studio without requiring any juggling inside `composer.json` (i.e. you should be able to keep the version constraint at "1.*" while your local Studio package is at "feature/my-feature").

The issue is that when you work on a local Studio package you need to redefine your `composer.json` to use the same tag/branch/ref which is checked out in the local Studio package at the moment.

Not sure about the exact reason why this juggling is required, have not dug that deep into the package code yet to know.

**Comment by franzliedke** [comment] 2017-12-01 18:04
Indeed, this will be fixed with #52 / #73. Thanks for your patience.

**Closed by franzliedke** 2017-12-01 18:04 UTC
