### ISSUE TITLE
Issue with library versions not being detected.

### ISSUE THREAD

**Issue by jonnywilliamson** [franzliedke/studio#58] opened 2016-04-12 10:17 UTC
I have been asked to leave this issue here, but I'm not sure I'll get the wording correct.

Basically, I attempted to use studio to clone a github library like this:

`studio create telegram-bot-sdk --git https://github.com/irazasyed/telegram-bot-sdk`

Then I went to my project root and attempted to require the library:

`composer require irazasyed/telegram-bot-sdk` expecting studio to create a symlink to the local copy. That didn't happen and all I got was the library saved in the vendor folder as normal.

Having spoken with @franzliedke, he suggested to try using the `dev-master` version for my composer require which I did:

`composer require irazasyed/telegram-bot-sdk:dev-master`  and suddenly everything worked\* fine. 

I hope this helps someone else.

*Well not actually the first time. There was a problem [creating the symlink](https://github.com/franzliedke/studio/issues/57) but that was fixed by running vagrant as admin.

**Comment by TiGR** [comment] 2016-10-25 15:44
@franzliedke this is still not working. And as regarding your question in #55 - nope, adding new commit does not work. Even if you add new tag - it still does not work.

If you have version tag specification in composer require - studio just does not kick in. It works if it is `dev-master`, that is in source mode. Could this be fixed, please?

**Comment by rask** [comment] 2016-11-07 10:34
Would this require overwriting the Composer `LibraryInstaller` to bypass version constraint checks or is that logic too deep in the Composer core for a plugin to override properly?

**Comment by fredrkr** [comment] 2016-11-28 15:50
I echo this issue with an added caveat. Since my packages are somewhat interdependent, I have to update all composer.json-files involved and require "dev-develop" for studio to work. It's does become a bit of a hassle.

**Comment by rask** [comment] 2016-11-29 08:08
@fredrkr same here, I create temporary branches where I flip from `dev-master` to `dev-develop` in order to keep libraries in development state.

**Comment by franzliedke** [comment] 2017-12-02 20:43
Please try out the newly released [0.14.0-beta1 version](https://github.com/franzliedke/studio/releases/tag/0.14.0-beta1). I am hoping this issue will be gone.

(Note that you will have to run `composer update` and `composer dump-autoload` for the installation of any package.)

**Comment by franzliedke** [comment] 2018-11-24 13:44
Cannot reproduce the problem with the latest beta version, so I am closing this. :smiley:

**Closed by franzliedke** 2018-11-24 13:44 UTC
Labels: bug
